// Step 10: write RUN_REPORT.md from what the database recorded (releases, counts, runs, spend,
// models, anchors, themes). Every number here is read, not typed.
//   node src/report.js
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { resolve } from 'node:path';
import { openDb, getMeta, ROOT } from './lib/db.js';
import { COST, MODEL, FILTERS, UNCERTAIN_CONFIDENCE, TOP_TASKS } from '../config/weights.js';
import { SELECTED, QUESTION_SET_LABEL, questionSetHash } from '../config/questions.js';

const meta = (db, k) => { const v = getMeta(db, k); return v ? JSON.parse(v) : null; };
const usd = (x, d = 4) => `$${x.toFixed(d)}`;
const big = (x) => (x >= 1e12 ? `$${(x / 1e12).toFixed(2)}T` : x >= 1e9 ? `$${(x / 1e9).toFixed(2)}B` : `$${(x / 1e6).toFixed(1)}M`);
const md = (s) => String(s ?? '').replace(/\|/g, '\\|');
const dur = (s) => (s == null ? 'not recorded' : s >= 60 ? `${Math.floor(s / 60)} min ${s % 60} s` : `${s} s`);

function main() {
  const db = openDb();
  const onet = meta(db, 'onet');
  const bls = meta(db, 'bls');
  const spend = meta(db, 'design_spend');
  const selection = meta(db, 'design_selection');
  const rank = meta(db, 'rank');
  const qset = questionSetHash(MODEL);
  const runs = db.prepare('SELECT * FROM runs ORDER BY run_id').all();
  const scoringCost = runs.reduce((s, r) => s + (r.cost_usd || 0), 0);
  const scoringTokens = runs.reduce((s, r) => s + (r.input_tokens || 0), 0);
  const outTokens = runs.reduce((s, r) => s + (r.output_tokens || 0), 0);
  const models = db.prepare('SELECT model_reported m, COUNT(*) n FROM jev_answers GROUP BY 1').all();
  const designModels = db.prepare('SELECT model_reported m, COUNT(*) n FROM design_answers GROUP BY 1').all();
  const nullRequestIds = db.prepare('SELECT COUNT(*) n FROM jev_answers WHERE request_id IS NULL').get().n
    + db.prepare('SELECT COUNT(*) n FROM design_answers WHERE request_id IS NULL').get().n;
  const errors = db.prepare('SELECT COUNT(*) n FROM request_errors').get().n;
  const themesPath = resolve(ROOT, 'data', 'themes_ranked.json');
  const themes = existsSync(themesPath) ? JSON.parse(readFileSync(themesPath, 'utf8')) : null;
  const changed = Object.entries(SELECTED).filter(([, s]) => s.variant !== 'v1');
  const c = rank?.counts;
  const s = bls.summary;
  const match = Object.fromEntries(s.occupations_by_match.map((m) => [m.bls_match, m]));
  const firstRun = runs[0]?.started_at;
  const lastRun = runs.at(-1)?.finished_at;

  const L = [];
  L.push('# Run report', '',
    `Generated by \`src/report.js\` from data/scanner.db on ${new Date().toISOString().slice(0, 10)}. Items marked **(unconfirmed)** could not be checked from inside this run.`, '');

  L.push('## Releases and sources', '',
    '| Source | Release | Retrieved from | Integrity |', '|---|---|---|---|',
    `| O*NET | ${onet.version} (${onet.release}) | ${onet.url} (found on ${onet.database_page}) | ${onet.bytes.toLocaleString('en-US')} bytes, sha256 \`${onet.sha256}\`, downloaded ${onet.downloaded_at} |`,
    `| BLS OEWS | ${bls.release} (release code ${bls.release_code}), national, cross-industry | POST ${bls.source.url} (the BLS OEWS query service behind ${bls.source.tool}) | ${bls.rows} occupation rows, saved response sha256 \`${bls.sha256}\`, downloaded ${bls.downloaded_at} |`,
    '',
    `The official OEWS national flat file was tried first and refused: ${bls.attempts.map((a) => `${a.url} -> HTTP ${a.status}`).join('; ')}. `
      + 'The responses were BLS\'s bot-filter pages, not proxy errors. The query service serves the same published May 2025 estimates. **(unconfirmed)**: no row-by-row comparison against the flat file was possible.',
    '');

  L.push('## Ingest counts', '',
    `- O*NET: ${onet.counts.occupations} occupations (${onet.counts.occupations_with_tasks} with task statements), ${onet.counts.tasks.toLocaleString('en-US')} tasks, `
      + `${onet.counts.ratings.toLocaleString('en-US')} task ratings (${onet.counts.tasks_rated.toLocaleString('en-US')} tasks rated), Work Context for ${onet.counts.occupations_with_work_context} occupations, `
      + `${onet.counts.dwas.toLocaleString('en-US')} Detailed Work Activities with ${onet.counts.task_dwa_links.toLocaleString('en-US')} task links (every task has at least one).`,
    `- BLS join (first 7 characters of the O*NET code): exact ${match.exact.n} occupations (${match.exact.with_tasks} with tasks); broad-group residual ${match.broad_residual.n} (${match.broad_residual.with_tasks}); `
      + `minor-group residual ${match.minor_residual?.n ?? 0} (${match.minor_residual?.with_tasks ?? 0}); unmatched, flagged ${match.unmatched.n} (${match.unmatched.with_tasks} with tasks). `
      + 'A BLS row shared by several O*NET occupations is split evenly among those with tasks, so employment is not double counted.',
    `- Wages: ${s.wage_sources.map((w) => `${w.wage_source} ${w.n}`).join(', ')} (rule: ${bls.wage_rule}).`,
    `- Task shares within an occupation: ${s.share_methods.map((m) => `${m.share_method} ${m.n} occupations`).join(', ')}.`,
    `- Labor value: ${s.tasks_with_labor_value.toLocaleString('en-US')} tasks have one, ${s.tasks_without_labor_value} do not (their scale falls back to volume/3). `
      + `Sum of occupation wage bills ${big(s.total_wage_bill)}; sum of task labor values ${big(s.total_labor_value)} (occupations without task statements carry no tasks). `
      + 'These are estimates of what employers pay for the work today (employment x median wage x task share), not market sizes.',
    '');

  L.push('## Question design', '',
    `See QUESTION_DESIGN.md. ${designModels.reduce((a, m) => a + m.n, 0)} labeled-task calls plus 1 smoke-test call: ${spend.requests} requests, `
      + `${spend.input_tokens.toLocaleString('en-US')} input tokens, ${usd(spend.cost_usd)} (cap $2).`,
    `- Every concept is asked of Jev; no O*NET-derived measure came within 0.02 of the best Jev variant.`,
    `- Changes from the original draft: \`recoverable_loss\` split into \`errors_lose_money\` x \`loss_recoverable\`; \`sell_model\` gained an \`other\` option; `
      + `the state now includes the task's O*NET Detailed Work Activities; ${changed.length} concepts use a rewritten variant: ${changed.map(([k, v]) => `${k} (${v.variant})`).join(', ')}.`,
    `- Below target on held-out: ${Object.entries(selection.selection).filter(([, x]) => !x.meets_target_heldout).map(([k, x]) => `${k} (${x.heldout.metric.toFixed(2)} vs ${x.target})`).join(', ') || 'none'}.`,
    `- Correlations above 0.85 between chosen measures: ${selection.high_correlations.length || 'none'}.`,
    '');

  L.push('## Jev scoring runs', '',
    `Question set \`${qset}\` (${QUESTION_SET_LABEL}), model requested \`${MODEL}\`. Cost is computed at $${COST.usdPerMillionInputTokens} per million input tokens from the `
      + 'input_tokens the API reported; output tokens are priced at $0 per the plan. **(unconfirmed)**: not reconciled with a TypeSafe invoice.', '',
    '| Run | Mode | Tasks asked | Cached | Requests OK | Failed attempts | Input tokens | Output tokens | Cost | Duration | Status |',
    '|---:|---|---:|---:|---:|---:|---:|---:|---:|---|---|',
    ...runs.map((r) => { const n = JSON.parse(r.notes || '{}'); return `| ${r.run_id} | ${n.mode || r.mode} | ${r.tasks_planned} | ${r.tasks_cached} | ${r.requests_ok} | ${r.requests_failed} | ${(r.input_tokens || 0).toLocaleString('en-US')} | ${(r.output_tokens || 0).toLocaleString('en-US')} | ${usd(r.cost_usd || 0)} | ${dur(n.seconds)} | ${r.status} |`; }),
    '',
    `- Scoring total: ${scoringTokens.toLocaleString('en-US')} input tokens (${outTokens.toLocaleString('en-US')} output), ${usd(scoringCost)} of the $${COST.capUsd} cap. `
      + `All Jev spend including question design: ${usd(scoringCost + spend.cost_usd)}.`,
    `- Models reported by the API: scoring ${models.map((m) => `\`${m.m}\` x ${m.n.toLocaleString('en-US')}`).join(', ')}; question design ${designModels.map((m) => `\`${m.m}\` x ${m.n}`).join(', ')}.`,
    `- Request IDs recorded for every answer: ${nullRequestIds === 0 ? 'yes' : `no, ${nullRequestIds} missing`}. Request errors logged: ${errors}.`,
    `- Wall time from the first scoring run's start to the last one's end: ${firstRun} to ${lastRun}.`,
    '');

  if (c) {
    L.push('## Counts', '',
      '| | Tasks |', '|---|---:|',
      `| O*NET tasks | ${c.tasks_total.toLocaleString('en-US')} |`,
      `| Scored by Jev | ${c.tasks_scored.toLocaleString('en-US')} |`,
      `| Removed by filters (physical >= ${FILTERS.physicalDropAtOrAbove} or reads_text < ${FILTERS.readsTextDropBelow}) | ${c.filtered_total.toLocaleString('en-US')} |`,
      `| - physical only / reads_text only / both | ${c.filtered_physical_only} / ${c.filtered_reads_text_only.toLocaleString('en-US')} / ${c.filtered_both.toLocaleString('en-US')} |`,
      `| Kept and ranked | ${c.kept.toLocaleString('en-US')} |`,
      `| Uncertain (a Score answer with confidence < ${UNCERTAIN_CONFIDENCE}): all scored / kept / top ${TOP_TASKS} | ${c.uncertain_all_scored.toLocaleString('en-US')} / ${c.uncertain_kept.toLocaleString('en-US')} / ${c.uncertain_top} |`,
      `| Kept tasks whose scale came from volume/3 (no wage data) | ${c.scale_from_volume_kept} |`,
      '');
  }

  const a = selection.anchor_check;
  L.push('## Anchor results', '',
    '| Check | High anchors (target 12/15) | Low anchors (target 12/15) |', '|---|---|---|',
    `| Labeled set (270 tasks), top / bottom quarter | ${a.high_in_top_quarter}/15 in top quarter | ${a.low_in_bottom_quarter}/15 in bottom quarter; ${a.low_removed_by_filters}/15 removed by the filters |`,
    rank ? `| Full ranking (${rank.anchors.scored_tasks.toLocaleString('en-US')} tasks), top / bottom quarter | ${rank.anchors.high_in_top_quarter}/15 in top quarter; ${rank.anchors.high_in_top_300}/15 in the top ${TOP_TASKS} | ${rank.anchors.low_in_bottom_quarter}/15 in bottom quarter; ${rank.anchors.low_removed_by_filters}/15 removed by the filters |` : '',
    '',
    'The low side fails as worded because the filters remove most tasks and physical work enters only through the filter, so the order inside the filtered group says nothing about fit. '
      + 'No low anchor can appear in the ranked output. Details and options are in QUESTION_DESIGN.md (E3); the formula was left as specified.',
    '');

  if (themes) {
    L.push('## Top 10 themes', '',
      'From out/themes.md (ranked by total labor value x average opportunity; labor value is an estimate).', '',
      '| # | Theme | Tasks | Total labor value | Avg opportunity | Main buyer | Main sell model |', '|---:|---|---:|---:|---:|---|---|',
      ...themes.slice(0, 10).map((t) => `| ${t.theme_id} | ${md(t.name)} | ${t.n} | ${big(t.total_labor_value)} | ${t.average_opportunity.toFixed(3)} | ${t.buyer} | ${t.sell_model} |`),
      '');
  }

  L.push('## Not confirmed', '',
    '- Dollar cost: computed from reported tokens at the published price; not checked against billing.',
    '- BLS numbers came from the query service, not the flat file (see above).',
    '- The labeled set used to choose questions is AI-labeler judgment, adjudicated by Claude, not ground truth; the two labelers are the same model family, so their agreement overstates reliability.',
    '- Labor value, theme totals and brief size estimates are estimates built from national medians and task-importance shares.',
    '- Jev\'s buyer and sell-model answers are model judgments; the briefs treat them as hypotheses to validate.',
    '');

  writeFileSync(resolve(ROOT, 'RUN_REPORT.md'), L.filter((x) => x !== null).join('\n'));
  console.log('wrote RUN_REPORT.md');
}

main();
